stages:
  - checks
  - second_stage_checks
  - build
  - publish

.checks_template:
  stage: checks
  image:  gitlab-registry.cern.ch/bozek/hepdata-docker:master-c081f579
  before_script:
   - echo "Pip-installing hepdata_submission_maker"
   - pip3 install --upgrade --editable .

unittests_checks:
  extends: .checks_template
  script:
   - echo "Running unit tests!"
   - pytest -r sx --ignore tests/full_workflow/

mypy_static_typing_checs:
  stage: checks
  image: python:latest
  script:
    - pip3 install --upgrade --editable .
    - pip3 install mypy
    - mypy src/hepdata_maker
  allow_failure: true

#
## Example 1
example1_record_creation:
  extends: .checks_template
  script:
   - echo "Example1"
   - tar -zxvf 	examples/example1.tar.gz
   - hepdata_maker create-submission examples/example1_result/steering_file.json
   - mv submission.tar.gz submission_example1.tar.gz
  artifacts:
    paths:
     - submission_example1.tar.gz
    expire_in: 1 hour

# To implement checks for examples available
#example1_record_check:
#  stage: second_stage_checks
#  image: python:latest
#  script:
#   - python tests/full_workflow/test_stop0L_example.py
#  dependencies:
#    - example1_record_creation
#

example1_record_upload:
  stage: second_stage_checks
  image: python:latest
  script:
   - pip3 install hepdata_cli
   - hepdata-cli upload submission_example1.tar.gz -e "$SECRET_EMAIL_HEPDATA" -r 1630351529 -s True -p "$SECRET_PASSWORD_HEPDATA"
  dependencies:
    - example1_record_creation
  only:
    - master
##
#

#
## Example 2
example2_record_creation:
  extends: .checks_template
  script:
   - echo "Example2"
   - tar -zxvf 	examples/example2.tar.gz
   - hepdata_maker create-submission examples/example2_result/steering_file.json
   - mv submission.tar.gz submission_example2.tar.gz
  artifacts:
    paths:
     - submission_example2.tar.gz
    expire_in: 1 hour

example2_record_upload:
  stage: second_stage_checks
  image: python:latest
  script:
   - pip3 install hepdata_cli
   - hepdata-cli upload submission_example2.tar.gz -e "$SECRET_EMAIL_HEPDATA" -r 1630354586 -s True -p "$SECRET_PASSWORD_HEPDATA"
  dependencies:
    - example2_record_creation
  only:
    - master
##
#

#
## Example 3
example3_record_creation:
  extends: .checks_template
  script:
   - echo "Example3"
   - tar -zxvf 	examples/example3.tar.gz
   - ln -s examples/example3_result/steering_file.json .
   - hepdata_maker create-submission steering_file.json
   - mv submission.tar.gz submission_example3.tar.gz
  artifacts:
    paths:
     - submission_example3.tar.gz
    expire_in: 1 hour

example3_record_upload:
  stage: second_stage_checks
  image: python:latest
  script:
   - pip3 install hepdata_cli
   - hepdata-cli upload submission_example3.tar.gz -e "$SECRET_EMAIL_HEPDATA" -r 1630357014 -s True -p "$SECRET_PASSWORD_HEPDATA"
  dependencies:
    - example3_record_creation
  only:
    - master
##
#

#
## Example 4
example4_record_creation:
  extends: .checks_template
  script:
   - echo "Example4"
   - tar -zxvf 	examples/example4.tar.gz
   - hepdata_maker create-submission examples/example4_result/steering_file.json
   - mv submission.tar.gz submission_example4.tar.gz
  artifacts:
    paths:
     - submission_example4.tar.gz
    expire_in: 1 hour

example4_record_upload:
  stage: second_stage_checks
  image: python:latest
  script:
   - pip3 install hepdata_cli
   - hepdata-cli upload submission_example4.tar.gz -e "$SECRET_EMAIL_HEPDATA" -r 1630362142 -s True -p "$SECRET_PASSWORD_HEPDATA"
  dependencies:
    - example4_record_creation
  only:
    - master
##
#

#
## Example 5
example5_record_creation:
  extends: .checks_template
  script:
   - echo "Example5"
   - tar -zxvf 	examples/example5.tar.gz
   - hepdata_maker create-submission examples/example5_result/steering_file.json
   - mv submission.tar.gz submission_example5.tar.gz
  artifacts:
    paths:
     - submission_example5.tar.gz
    expire_in: 1 hour

example5_record_upload:
  stage: second_stage_checks
  image: python:latest
  script:
   - pip3 install hepdata_cli
   - hepdata-cli upload submission_example5.tar.gz -e "$SECRET_EMAIL_HEPDATA" -r 1630363616 -s True -p "$SECRET_PASSWORD_HEPDATA"
  dependencies:
    - example5_record_creation
  only:
    - master
##
#

#
## Example 6
example6_record_creation:
  extends: .checks_template
  script:
   - echo "Example6"
   - tar -zxvf 	examples/example6.tar.gz
   - hepdata_maker create-submission examples/example6_result/steering_file.json
   - mv submission.tar.gz submission_example6.tar.gz
  artifacts:
    paths:
     - submission_example6.tar.gz
    expire_in: 1 hour

example6_record_upload:
  stage: second_stage_checks
  image: python:latest
  script:
   - pip3 install hepdata_cli
   - hepdata-cli upload submission_example6.tar.gz -e "$SECRET_EMAIL_HEPDATA" -r 1630365204 -s True -p "$SECRET_PASSWORD_HEPDATA"
  dependencies:
    - example6_record_creation
  only:
    - master
##
#

#
## Example 7
example7_record_creation:
  extends: .checks_template
  script:
   - echo "Example7"
   - tar -zxvf 	examples/example7.tar.gz
   - hepdata_maker create-submission examples/example7_result/steering_file.json
   - mv submission.tar.gz submission_example7.tar.gz
  artifacts:
    paths:
     - submission_example7.tar.gz
    expire_in: 1 hour

example7_record_upload:
  stage: second_stage_checks
  image: python:latest
  script:
   - pip3 install hepdata_cli
   - hepdata-cli upload submission_example7.tar.gz -e "$SECRET_EMAIL_HEPDATA" -r 1630367107 -s True -p "$SECRET_PASSWORD_HEPDATA"
  dependencies:
    - example7_record_creation
  only:
    - master
##
#

#
## Example 8
example8_record_creation:
  extends: .checks_template
  script:
   - echo "Example8"
   - tar -zxvf 	examples/example8.tar.gz
   - hepdata_maker create-submission example8/main_steering_file.json --data-root example8/
   - mv submission.tar.gz submission_example8.tar.gz
  artifacts:
    paths:
     - submission_example8.tar.gz
    expire_in: 1 hour

example8_record_upload:
  stage: second_stage_checks
  image: python:latest
  script:
   - pip3 install hepdata_cli
   - hepdata-cli upload submission_example8.tar.gz -e "$SECRET_EMAIL_HEPDATA" -r 1630400334 -s True -p "$SECRET_PASSWORD_HEPDATA"
  dependencies:
    - example8_record_creation
  only:
    - master
##
#


.template_check_hepdata_conversions:
  extends: .checks_template
  script:
    - wget "$URL_HEPDATA_RECORD" -O orig_submission.zip
    - unzip -d orig_submission orig_submission.zip
    - hepdata_maker hepdata-to-steering-file -d orig_submission
    - hepdata_maker create-submission steering_file.json --use-fancy-names
    - python3 tests/compare_submissions.py orig_submission submission_files

check_hepdata_ins1851675:
  variables:
    URL_HEPDATA_RECORD: https://www.hepdata.net/download/submission/ins1851675/1/original
  extends: .template_check_hepdata_conversions

check_hepdata_TestHEPSubmission:
  variables:
    URL_HEPDATA_RECORD: https://hepdata-submission.readthedocs.io/en/latest/_downloads/626dbe93a9bb268f7de12fa9c2afdb73/TestHEPSubmission.zip
  extends: .template_check_hepdata_conversions

check_documentation:
  extends: .checks_template
  script:
    - pip3 install Sphinx sphinx-click sphinx-copybutton autoclass autoclasstoc
    - cd docs
    - make html SPHINXOPTS="-W"
  allow_failure: true

package_build:
  stage: build
  image: python:latest
  script:
   - python3 setup.py sdist
  artifacts:
    paths:
      - dist/hepdata_submission_maker-0.0.0.tar.gz
    expire_in: 1 week
    
package_publish:
  stage: publish
  script:
   - echo "To do if decided to publish package"
