stages:
  - checks
  - build
  - publish

scheme_checks:
  stage: checks
  image:  gitlab-registry.cern.ch/bozek/hepdata-docker:master-072a0b4b
  script:
   - echo "Running unit tests!"
   - pip3 install --upgrade --editable .
   - pytest -r sx

package_build:
  stage: build
  image: python:latest
  script:
   - python3 setup.py sdist
  artifacts:
    paths:
      - dist/hepdata_submission_maker-0.0.0.tar.gz
    expire_in: 1 week
    
package_publish:
  stage: publish
  script:
   - echo "To do if decided to publish package"
