stages:
  - checks
  - second_stage_checks
  - build
  - publish

.checks_template:
  stage: checks
  image:  gitlab-registry.cern.ch/bozek/hepdata-docker:master-c081f579
  before_script:
   - echo "Pip-installing hepdata_submission_maker"
   - pip3 install --upgrade --editable .

unittests_checks:
  extends: .checks_template
  script:
   - echo "Running unit tests!"
   - pytest -r sx --ignore tests/full_workflow/

mypy_static_typing_checs:
  stage: checks
  image: python:latest
  script:
    - pip3 install --upgrade --editable .
    - pip3 install mypy
    - mypy src/hepdata_maker
  allow_failure: true

example1_record_creation:
  extends: .checks_template
  script:
   - echo "'pseudo' stop0L record creation!"
   - hepdata_maker create-submission examples/stop0L/submissions_config.json
  artifacts:
    paths:
     - submission.tar.gz
    expire_in: 1 hour

example1_record_check:
  stage: second_stage_checks
  image: python:latest
  script:
   - python tests/full_workflow/test_stop0L_example.py
  dependencies:
    - example1_record_creation

example1_record_upload:
  stage: second_stage_checks
  image: python:latest
  script:
   - pip3 install hepdata_cli
   - hepdata-cli upload submission.tar.gz -e "$SECRET_EMAIL_HEPDATA" -r 1629808138 -s True -p "$SECRET_PASSWORD_HEPDATA"
  dependencies:
    - example1_record_creation
  only:
    - master

.template_check_hepdata_conversions:
  extends: .checks_template
  script:
    - wget "$URL_HEPDATA_RECORD" -O orig_submission.zip
    - unzip -d orig_submission orig_submission.zip
    - hepdata_maker hepdata-to-steering-file -d orig_submission
    - hepdata_maker create-submission steering_file.json --use-fancy-names
    - python3 tests/compare_submissions.py orig_submission submission_files

check_hepdata_ins1851675:
  variables:
    URL_HEPDATA_RECORD: https://www.hepdata.net/download/submission/ins1851675/1/original
  extends: .template_check_hepdata_conversions

check_hepdata_TestHEPSubmission:
  variables:
    URL_HEPDATA_RECORD: https://hepdata-submission.readthedocs.io/en/latest/_downloads/626dbe93a9bb268f7de12fa9c2afdb73/TestHEPSubmission.zip
  extends: .template_check_hepdata_conversions

check_documentation
  extends: .checks_template
  script:
    - pip3 install Sphinx sphinx-click sphinx-copybutton autoclass autoclasstoc
    - cd docs
    - make html SPHINXOPTS="-W"
    
package_build:
  stage: build
  image: python:latest
  script:
   - python3 setup.py sdist
  artifacts:
    paths:
      - dist/hepdata_submission_maker-0.0.0.tar.gz
    expire_in: 1 week
    
package_publish:
  stage: publish
  script:
   - echo "To do if decided to publish package"
